sudo: required
services: 
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_b12209fd5256_key -iv $encrypted_b12209fd5256_iv -in multi-k8s-388909-295a9a40a2e4.json.enc -out multi-k8s-388909-295a9a40a2e4.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
